name: Checks

on:[push] # trigger

jobs: # 실행 workflow management
  test-lint: #github에서 우리 코드를 받아와서 실행?
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login in to docker Hub
        uses: docker/login-action@v1 # actions에서 docker container로 접근하기 위한 패키지 설치
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout 
        uses: actions/checkout@v2 #깃헙에 올라온 checkout actions을 불러와서 실행
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test" #test는 기본적으로 django에서 만들어줌
      - name: Lint(Flake8)
        run: docker compose run --rm app sh -c "flake8"
# jenkins
# github actions > 무료 (설치 필요 x)